return { "Biscuit-Colorscheme/nvim",
  "onur-ozkan/nimda.vim",
  "savq/melange-nvim",
  'sainnhe/gruvbox-material',
  'jacoborus/tender.vim',
  'xero/miasma.nvim',
  "fynnfluegge/monet.nvim",
  'AhmedAbdulrahman/aylin.vim',
  {'srcery-colors/srcery-vim', as = 'srcery'},
  "olimorris/onedarkpro.nvim",
  'AlexvZyl/nordic.nvim',
  'rhysd/vim-color-spring-night',
  'frenzyexists/aquarium-vim',
  "lunarvim/horizon.nvim",
  'Shadorain/shadotheme',
  "neanias/everforest-nvim",
  "rayes0/blossom.vim",
  "ellisonleao/gruvbox.nvim",
  {'mountain-theme/vim', as = "mountain" },
  'perpetuatheme/nvim',
  "aereal/vim-colors-japanesque",
  "cocopon/iceberg.vim",
  "CrispyBaccoon/evergarden",
  "daschw/leaf.nvim",
  { "catppuccin/nvim", as = "catppuccin" },
  "kihachi2000/yash.nvim",
  "nanotech/jellybeans.vim",
  "Enonya/yuyuko.vim",
  "tobi-wan-kenobi/zengarden",
  "nyoom-engineering/nyoom.nvim",
  { 'Biscuit-Theme/nvim', as = "biscuit",},
  {"nyoom-engineering/nyoom.nvim", as = "nyoom" },

}
